// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_findings.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getOrCreateAgentScanReport = `-- name: GetOrCreateAgentScanReport :one
WITH existing AS (
    SELECT id, engagement_id, source_type, original_filename, storage_uri,
           sha256, scan_date, ingested_at, parser_version, parse_status,
           parse_error, finding_count, uploaded_by
    FROM scan_reports
    WHERE engagement_id = $1::bigint
      AND sha256        = $2::text
      AND source_type   = 'agent'
    LIMIT 1
), inserted AS (
    INSERT INTO scan_reports (
        engagement_id, source_type, original_filename, storage_uri,
        sha256, parser_version, uploaded_by, parse_status
    )
    SELECT $1::bigint, 'agent',
           $3::text,
           $4::text,
           $2::text, 'agent-v1',
           $5::bigint, 'succeeded'
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    RETURNING id, engagement_id, source_type, original_filename, storage_uri,
              sha256, scan_date, ingested_at, parser_version, parse_status,
              parse_error, finding_count, uploaded_by
)
SELECT id, engagement_id, source_type, original_filename, storage_uri,
       sha256, scan_date, ingested_at, parser_version, parse_status,
       parse_error, finding_count, uploaded_by
FROM existing
UNION ALL
SELECT id, engagement_id, source_type, original_filename, storage_uri,
       sha256, scan_date, ingested_at, parser_version, parse_status,
       parse_error, finding_count, uploaded_by
FROM inserted
`

type GetOrCreateAgentScanReportParams struct {
	EngagementID     int64  `json:"engagement_id"`
	Sha256           string `json:"sha256"`
	OriginalFilename string `json:"original_filename"`
	StorageUri       string `json:"storage_uri"`
	UploadedBy       int64  `json:"uploaded_by"`
}

type GetOrCreateAgentScanReportRow struct {
	ID               int64          `json:"id"`
	EngagementID     int64          `json:"engagement_id"`
	SourceType       ScanSourceType `json:"source_type"`
	OriginalFilename string         `json:"original_filename"`
	StorageUri       string         `json:"storage_uri"`
	Sha256           string         `json:"sha256"`
	ScanDate         sql.NullTime   `json:"scan_date"`
	IngestedAt       time.Time      `json:"ingested_at"`
	ParserVersion    string         `json:"parser_version"`
	ParseStatus      ParseStatus    `json:"parse_status"`
	ParseError       sql.NullString `json:"parse_error"`
	FindingCount     int32          `json:"finding_count"`
	UploadedBy       int64          `json:"uploaded_by"`
}

// Returns the scan_report row that holds agent-recorded findings for the
// given (engagement_id, flow-deterministic sha256) pair, creating one on
// the first call. Re-entrant tool calls within the same flow share the
// same scan_report so the findings table stays tidy (one agent-source row
// per flow, not one per finding).
func (q *Queries) GetOrCreateAgentScanReport(ctx context.Context, arg GetOrCreateAgentScanReportParams) (GetOrCreateAgentScanReportRow, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateAgentScanReport,
		arg.EngagementID,
		arg.Sha256,
		arg.OriginalFilename,
		arg.StorageUri,
		arg.UploadedBy,
	)
	var i GetOrCreateAgentScanReportRow
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.SourceType,
		&i.OriginalFilename,
		&i.StorageUri,
		&i.Sha256,
		&i.ScanDate,
		&i.IngestedAt,
		&i.ParserVersion,
		&i.ParseStatus,
		&i.ParseError,
		&i.FindingCount,
		&i.UploadedBy,
	)
	return i, err
}
