// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: engagements.sql

package database

import (
	"context"
	"database/sql"
)

const addScopeRule = `-- name: AddScopeRule :one
INSERT INTO engagement_scope_rules
  (engagement_id, rule_type, value, direction, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, engagement_id, rule_type, value, direction, note, created_at
`

type AddScopeRuleParams struct {
	EngagementID int64          `json:"engagement_id"`
	RuleType     ScopeRuleType  `json:"rule_type"`
	Value        string         `json:"value"`
	Direction    ScopeDirection `json:"direction"`
	Note         sql.NullString `json:"note"`
}

func (q *Queries) AddScopeRule(ctx context.Context, arg AddScopeRuleParams) (EngagementScopeRule, error) {
	row := q.db.QueryRowContext(ctx, addScopeRule,
		arg.EngagementID,
		arg.RuleType,
		arg.Value,
		arg.Direction,
		arg.Note,
	)
	var i EngagementScopeRule
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.RuleType,
		&i.Value,
		&i.Direction,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createEngagement = `-- name: CreateEngagement :one
INSERT INTO engagements (
  name, client, description, graphiti_group_id,
  starts_at, ends_at, created_by, updated_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, name, client, description, status, graphiti_group_id, starts_at, ends_at, created_by, updated_by, team_id, created_at, updated_at, deleted_at
`

type CreateEngagementParams struct {
	Name            string         `json:"name"`
	Client          string         `json:"client"`
	Description     sql.NullString `json:"description"`
	GraphitiGroupID string         `json:"graphiti_group_id"`
	StartsAt        sql.NullTime   `json:"starts_at"`
	EndsAt          sql.NullTime   `json:"ends_at"`
	CreatedBy       int64          `json:"created_by"`
}

func (q *Queries) CreateEngagement(ctx context.Context, arg CreateEngagementParams) (Engagement, error) {
	row := q.db.QueryRowContext(ctx, createEngagement,
		arg.Name,
		arg.Client,
		arg.Description,
		arg.GraphitiGroupID,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Engagement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Description,
		&i.Status,
		&i.GraphitiGroupID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteScopeRule = `-- name: DeleteScopeRule :exec
DELETE FROM engagement_scope_rules
WHERE id = $1 AND engagement_id = $2
`

type DeleteScopeRuleParams struct {
	ID           int64 `json:"id"`
	EngagementID int64 `json:"engagement_id"`
}

func (q *Queries) DeleteScopeRule(ctx context.Context, arg DeleteScopeRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteScopeRule, arg.ID, arg.EngagementID)
	return err
}

const engagementFindingStats = `-- name: EngagementFindingStats :one
SELECT
  count(*) FILTER (WHERE severity = 'critical') AS critical_count,
  count(*) FILTER (WHERE severity = 'high')     AS high_count,
  count(*) FILTER (WHERE severity = 'medium')   AS medium_count,
  count(*) FILTER (WHERE severity = 'low')      AS low_count,
  count(*) FILTER (WHERE severity = 'info')     AS info_count,
  count(*) FILTER (WHERE in_scope = false)      AS oos_count,
  count(*) FILTER (WHERE verification_status = 'confirmed') AS confirmed_count
FROM findings WHERE engagement_id = $1
`

type EngagementFindingStatsRow struct {
	CriticalCount  int64 `json:"critical_count"`
	HighCount      int64 `json:"high_count"`
	MediumCount    int64 `json:"medium_count"`
	LowCount       int64 `json:"low_count"`
	InfoCount      int64 `json:"info_count"`
	OosCount       int64 `json:"oos_count"`
	ConfirmedCount int64 `json:"confirmed_count"`
}

func (q *Queries) EngagementFindingStats(ctx context.Context, engagementID int64) (EngagementFindingStatsRow, error) {
	row := q.db.QueryRowContext(ctx, engagementFindingStats, engagementID)
	var i EngagementFindingStatsRow
	err := row.Scan(
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.InfoCount,
		&i.OosCount,
		&i.ConfirmedCount,
	)
	return i, err
}

const getEngagement = `-- name: GetEngagement :one
SELECT id, name, client, description, status, graphiti_group_id, starts_at, ends_at, created_by, updated_by, team_id, created_at, updated_at, deleted_at FROM engagements
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEngagement(ctx context.Context, id int64) (Engagement, error) {
	row := q.db.QueryRowContext(ctx, getEngagement, id)
	var i Engagement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Description,
		&i.Status,
		&i.GraphitiGroupID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEngagements = `-- name: ListEngagements :many
SELECT id, name, client, description, status, graphiti_group_id, starts_at, ends_at, created_by, updated_by, team_id, created_at, updated_at, deleted_at FROM engagements
WHERE deleted_at IS NULL
  AND ($3::ENGAGEMENT_STATUS IS NULL OR status = $3::ENGAGEMENT_STATUS)
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListEngagementsParams struct {
	Limit  int64                `json:"limit"`
	Offset int64                `json:"offset"`
	Status NullEngagementStatus `json:"status"`
}

func (q *Queries) ListEngagements(ctx context.Context, arg ListEngagementsParams) ([]Engagement, error) {
	rows, err := q.db.QueryContext(ctx, listEngagements, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Engagement
	for rows.Next() {
		var i Engagement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Client,
			&i.Description,
			&i.Status,
			&i.GraphitiGroupID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeRules = `-- name: ListScopeRules :many
SELECT id, engagement_id, rule_type, value, direction, note, created_at FROM engagement_scope_rules
WHERE engagement_id = $1
ORDER BY id
`

func (q *Queries) ListScopeRules(ctx context.Context, engagementID int64) ([]EngagementScopeRule, error) {
	rows, err := q.db.QueryContext(ctx, listScopeRules, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EngagementScopeRule
	for rows.Next() {
		var i EngagementScopeRule
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.RuleType,
			&i.Value,
			&i.Direction,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEngagement = `-- name: SoftDeleteEngagement :exec
UPDATE engagements SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEngagement(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteEngagement, id)
	return err
}

const updateEngagement = `-- name: UpdateEngagement :one
UPDATE engagements
SET name        = COALESCE($3, name),
    client      = COALESCE($4, client),
    description = COALESCE($5, description),
    status      = COALESCE($6, status),
    starts_at   = COALESCE($7, starts_at),
    ends_at     = COALESCE($8, ends_at),
    updated_by  = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, client, description, status, graphiti_group_id, starts_at, ends_at, created_by, updated_by, team_id, created_at, updated_at, deleted_at
`

type UpdateEngagementParams struct {
	ID          int64                `json:"id"`
	UpdatedBy   int64                `json:"updated_by"`
	Name        sql.NullString       `json:"name"`
	Client      sql.NullString       `json:"client"`
	Description sql.NullString       `json:"description"`
	Status      NullEngagementStatus `json:"status"`
	StartsAt    sql.NullTime         `json:"starts_at"`
	EndsAt      sql.NullTime         `json:"ends_at"`
}

func (q *Queries) UpdateEngagement(ctx context.Context, arg UpdateEngagementParams) (Engagement, error) {
	row := q.db.QueryRowContext(ctx, updateEngagement,
		arg.ID,
		arg.UpdatedBy,
		arg.Name,
		arg.Client,
		arg.Description,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Engagement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Description,
		&i.Status,
		&i.GraphitiGroupID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
