// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: findings.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const attachFindingSource = `-- name: AttachFindingSource :exec
INSERT INTO finding_sources (finding_id, scan_report_id, source_evidence)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AttachFindingSourceParams struct {
	FindingID      int64           `json:"finding_id"`
	ScanReportID   int64           `json:"scan_report_id"`
	SourceEvidence json.RawMessage `json:"source_evidence"`
}

func (q *Queries) AttachFindingSource(ctx context.Context, arg AttachFindingSourceParams) error {
	_, err := q.db.ExecContext(ctx, attachFindingSource, arg.FindingID, arg.ScanReportID, arg.SourceEvidence)
	return err
}

const findingsByTargetKind = `-- name: FindingsByTargetKind :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings
WHERE engagement_id = $1 AND target_kind = $2 AND in_scope = true
ORDER BY severity DESC, cvss_score DESC NULLS LAST
`

type FindingsByTargetKindParams struct {
	EngagementID int64      `json:"engagement_id"`
	TargetKind   TargetKind `json:"target_kind"`
}

func (q *Queries) FindingsByTargetKind(ctx context.Context, arg FindingsByTargetKindParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, findingsByTargetKind, arg.EngagementID, arg.TargetKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsPendingGraphSync = `-- name: FindingsPendingGraphSync :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings WHERE graph_seeded_at IS NULL LIMIT $1
`

func (q *Queries) FindingsPendingGraphSync(ctx context.Context, limit int64) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, findingsPendingGraphSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinding = `-- name: GetFinding :one
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id int64) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.ScanReportID,
		&i.FindingType,
		&i.TargetKind,
		&i.TargetRef,
		&i.Title,
		&i.Cve,
		&i.CvssScore,
		&i.Severity,
		&i.Confidence,
		&i.SourceID,
		&i.Evidence,
		&i.InScope,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationNotes,
		&i.GraphSeededAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindings = `-- name: ListFindings :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings
WHERE engagement_id = $1
  AND ($4::SEVERITY_LEVEL          IS NULL OR severity            = $4::SEVERITY_LEVEL)
  AND ($5::text                          IS NULL OR cve                 = $5)
  AND ($6::TARGET_KIND           IS NULL OR target_kind         = $6::TARGET_KIND)
  AND ($7::boolean                  IS NULL OR in_scope            = $7::boolean)
  AND ($8::VERIFICATION_STATUS IS NULL OR verification_status = $8::VERIFICATION_STATUS)
ORDER BY
  CASE severity
    WHEN 'critical' THEN 5 WHEN 'high' THEN 4 WHEN 'medium' THEN 3
    WHEN 'low' THEN 2 ELSE 1
  END DESC,
  cvss_score DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListFindingsParams struct {
	EngagementID       int64                  `json:"engagement_id"`
	Limit              int64                  `json:"limit"`
	Offset             int64                  `json:"offset"`
	Severity           NullSeverityLevel      `json:"severity"`
	Cve                sql.NullString         `json:"cve"`
	TargetKind         NullTargetKind         `json:"target_kind"`
	InScope            sql.NullBool           `json:"in_scope"`
	VerificationStatus NullVerificationStatus `json:"verification_status"`
}

func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindings,
		arg.EngagementID,
		arg.Limit,
		arg.Offset,
		arg.Severity,
		arg.Cve,
		arg.TargetKind,
		arg.InScope,
		arg.VerificationStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFindingGraphSeeded = `-- name: MarkFindingGraphSeeded :exec
UPDATE findings SET graph_seeded_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) MarkFindingGraphSeeded(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markFindingGraphSeeded, id)
	return err
}

const topFindingsByCVSS = `-- name: TopFindingsByCVSS :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings
WHERE engagement_id = $1 AND in_scope = true
ORDER BY cvss_score DESC NULLS LAST, severity DESC
LIMIT $2
`

type TopFindingsByCVSSParams struct {
	EngagementID int64 `json:"engagement_id"`
	Limit        int64 `json:"limit"`
}

func (q *Queries) TopFindingsByCVSS(ctx context.Context, arg TopFindingsByCVSSParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, topFindingsByCVSS, arg.EngagementID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFindingVerification = `-- name: UpdateFindingVerification :one
UPDATE findings
SET verification_status = $2,
    verification_notes  = $3,
    verified_by         = $4,
    verified_at         = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at
`

type UpdateFindingVerificationParams struct {
	ID                 int64              `json:"id"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	VerificationNotes  sql.NullString     `json:"verification_notes"`
	VerifiedBy         sql.NullInt64      `json:"verified_by"`
}

func (q *Queries) UpdateFindingVerification(ctx context.Context, arg UpdateFindingVerificationParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingVerification,
		arg.ID,
		arg.VerificationStatus,
		arg.VerificationNotes,
		arg.VerifiedBy,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.ScanReportID,
		&i.FindingType,
		&i.TargetKind,
		&i.TargetRef,
		&i.Title,
		&i.Cve,
		&i.CvssScore,
		&i.Severity,
		&i.Confidence,
		&i.SourceID,
		&i.Evidence,
		&i.InScope,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationNotes,
		&i.GraphSeededAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (
  engagement_id, scan_report_id, finding_type, target_kind, target_ref,
  title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (engagement_id, target_ref, COALESCE(cve, ''), COALESCE(source_id, ''))
DO UPDATE SET
  last_seen_at = CURRENT_TIMESTAMP,
  cvss_score   = EXCLUDED.cvss_score,
  severity     = EXCLUDED.severity,
  confidence   = EXCLUDED.confidence,
  title        = EXCLUDED.title,
  evidence     = EXCLUDED.evidence,
  in_scope     = EXCLUDED.in_scope
RETURNING id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at, (xmax = 0) AS is_new
`

type UpsertFindingParams struct {
	EngagementID int64             `json:"engagement_id"`
	ScanReportID int64             `json:"scan_report_id"`
	FindingType  FindingType       `json:"finding_type"`
	TargetKind   TargetKind        `json:"target_kind"`
	TargetRef    string            `json:"target_ref"`
	Title        string            `json:"title"`
	Cve          sql.NullString    `json:"cve"`
	CvssScore    sql.NullString    `json:"cvss_score"`
	Severity     SeverityLevel     `json:"severity"`
	Confidence   FindingConfidence `json:"confidence"`
	SourceID     sql.NullString    `json:"source_id"`
	Evidence     json.RawMessage   `json:"evidence"`
	InScope      bool              `json:"in_scope"`
}

type UpsertFindingRow struct {
	ID                 int64              `json:"id"`
	EngagementID       int64              `json:"engagement_id"`
	ScanReportID       int64              `json:"scan_report_id"`
	FindingType        FindingType        `json:"finding_type"`
	TargetKind         TargetKind         `json:"target_kind"`
	TargetRef          string             `json:"target_ref"`
	Title              string             `json:"title"`
	Cve                sql.NullString     `json:"cve"`
	CvssScore          sql.NullString     `json:"cvss_score"`
	Severity           SeverityLevel      `json:"severity"`
	Confidence         FindingConfidence  `json:"confidence"`
	SourceID           sql.NullString     `json:"source_id"`
	Evidence           json.RawMessage    `json:"evidence"`
	InScope            bool               `json:"in_scope"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	VerifiedBy         sql.NullInt64      `json:"verified_by"`
	VerifiedAt         sql.NullTime       `json:"verified_at"`
	VerificationNotes  sql.NullString     `json:"verification_notes"`
	GraphSeededAt      sql.NullTime       `json:"graph_seeded_at"`
	FirstSeenAt        time.Time          `json:"first_seen_at"`
	LastSeenAt         time.Time          `json:"last_seen_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	IsNew              bool               `json:"is_new"`
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (UpsertFindingRow, error) {
	row := q.db.QueryRowContext(ctx, upsertFinding,
		arg.EngagementID,
		arg.ScanReportID,
		arg.FindingType,
		arg.TargetKind,
		arg.TargetRef,
		arg.Title,
		arg.Cve,
		arg.CvssScore,
		arg.Severity,
		arg.Confidence,
		arg.SourceID,
		arg.Evidence,
		arg.InScope,
	)
	var i UpsertFindingRow
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.ScanReportID,
		&i.FindingType,
		&i.TargetKind,
		&i.TargetRef,
		&i.Title,
		&i.Cve,
		&i.CvssScore,
		&i.Severity,
		&i.Confidence,
		&i.SourceID,
		&i.Evidence,
		&i.InScope,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationNotes,
		&i.GraphSeededAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsNew,
	)
	return i, err
}
