// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flow_retest.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const findingsByEngagement = `-- name: FindingsByEngagement :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings
WHERE engagement_id = $1
ORDER BY id
`

// All findings for the engagement. Used by the retest diff to compute the
// current set.
func (q *Queries) FindingsByEngagement(ctx context.Context, engagementID int64) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, findingsByEngagement, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsFirstSeenBefore = `-- name: FindingsFirstSeenBefore :many
SELECT id, engagement_id, scan_report_id, finding_type, target_kind, target_ref, title, cve, cvss_score, severity, confidence, source_id, evidence, in_scope, verification_status, verified_by, verified_at, verification_notes, graph_seeded_at, first_seen_at, last_seen_at, created_at, updated_at FROM findings
WHERE engagement_id = $1 AND first_seen_at <= $2
ORDER BY id
`

type FindingsFirstSeenBeforeParams struct {
	EngagementID int64     `json:"engagement_id"`
	FirstSeenAt  time.Time `json:"first_seen_at"`
}

// Findings in the engagement whose first_seen_at is at or before the given
// cutoff. Used by the retest diff to compute the baseline set.
func (q *Queries) FindingsFirstSeenBefore(ctx context.Context, arg FindingsFirstSeenBeforeParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, findingsFirstSeenBefore, arg.EngagementID, arg.FirstSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ScanReportID,
			&i.FindingType,
			&i.TargetKind,
			&i.TargetRef,
			&i.Title,
			&i.Cve,
			&i.CvssScore,
			&i.Severity,
			&i.Confidence,
			&i.SourceID,
			&i.Evidence,
			&i.InScope,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNotes,
			&i.GraphSeededAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFlowRetestDiff = `-- name: InsertFlowRetestDiff :exec
INSERT INTO flow_retest_diff (flow_id, finding_id, diff_state)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertFlowRetestDiffParams struct {
	FlowID    int64     `json:"flow_id"`
	FindingID int64     `json:"finding_id"`
	DiffState DiffState `json:"diff_state"`
}

func (q *Queries) InsertFlowRetestDiff(ctx context.Context, arg InsertFlowRetestDiffParams) error {
	_, err := q.db.ExecContext(ctx, insertFlowRetestDiff, arg.FlowID, arg.FindingID, arg.DiffState)
	return err
}

const insertFlowRetestTarget = `-- name: InsertFlowRetestTarget :exec

INSERT INTO flow_retest_targets (flow_id, finding_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertFlowRetestTargetParams struct {
	FlowID    int64 `json:"flow_id"`
	FindingID int64 `json:"finding_id"`
}

// Flow retest queries.
//
// Two tables feed the retest lifecycle:
//
//	flow_retest_targets — explicit list of finding IDs for
//	  targeted_reverify flows (the agent should only examine these).
//	flow_retest_diff — computed diff rows for retest_diff flows
//	  (fixed / persistent / new / regressed buckets).
//
// All queries are flow-scoped; the caller provides the flow ID.
func (q *Queries) InsertFlowRetestTarget(ctx context.Context, arg InsertFlowRetestTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertFlowRetestTarget, arg.FlowID, arg.FindingID)
	return err
}

const listFlowRetestDiff = `-- name: ListFlowRetestDiff :many
SELECT flow_id, finding_id, diff_state FROM flow_retest_diff WHERE flow_id = $1 ORDER BY finding_id
`

func (q *Queries) ListFlowRetestDiff(ctx context.Context, flowID int64) ([]FlowRetestDiff, error) {
	rows, err := q.db.QueryContext(ctx, listFlowRetestDiff, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowRetestDiff
	for rows.Next() {
		var i FlowRetestDiff
		if err := rows.Scan(&i.FlowID, &i.FindingID, &i.DiffState); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowRetestTargets = `-- name: ListFlowRetestTargets :many
SELECT finding_id FROM flow_retest_targets WHERE flow_id = $1 ORDER BY finding_id
`

func (q *Queries) ListFlowRetestTargets(ctx context.Context, flowID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listFlowRetestTargets, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var finding_id int64
		if err := rows.Scan(&finding_id); err != nil {
			return nil, err
		}
		items = append(items, finding_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowEngagement = `-- name: UpdateFlowEngagement :exec
UPDATE flows
SET engagement_id    = $2,
    flow_type        = $3,
    baseline_flow_id = $4
WHERE id = $1
`

type UpdateFlowEngagementParams struct {
	ID             int64         `json:"id"`
	EngagementID   sql.NullInt64 `json:"engagement_id"`
	FlowType       FlowType      `json:"flow_type"`
	BaselineFlowID sql.NullInt64 `json:"baseline_flow_id"`
}

// Populate engagement_id, flow_type, baseline_flow_id after the initial
// CreateFlow insert. CreateFlow has a fixed parameter list (title/model/…)
// that predates Phase 1; this :exec runs as a follow-up.
func (q *Queries) UpdateFlowEngagement(ctx context.Context, arg UpdateFlowEngagementParams) error {
	_, err := q.db.ExecContext(ctx, updateFlowEngagement,
		arg.ID,
		arg.EngagementID,
		arg.FlowType,
		arg.BaselineFlowID,
	)
	return err
}
