// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scan_reports.sql

package database

import (
	"context"
	"database/sql"
)

const createScanReport = `-- name: CreateScanReport :one
INSERT INTO scan_reports (
  engagement_id, source_type, original_filename, storage_uri,
  sha256, scan_date, parser_version, uploaded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, engagement_id, source_type, original_filename, storage_uri, sha256, scan_date, ingested_at, parser_version, parse_status, parse_error, finding_count, uploaded_by
`

type CreateScanReportParams struct {
	EngagementID     int64          `json:"engagement_id"`
	SourceType       ScanSourceType `json:"source_type"`
	OriginalFilename string         `json:"original_filename"`
	StorageUri       string         `json:"storage_uri"`
	Sha256           string         `json:"sha256"`
	ScanDate         sql.NullTime   `json:"scan_date"`
	ParserVersion    string         `json:"parser_version"`
	UploadedBy       int64          `json:"uploaded_by"`
}

func (q *Queries) CreateScanReport(ctx context.Context, arg CreateScanReportParams) (ScanReport, error) {
	row := q.db.QueryRowContext(ctx, createScanReport,
		arg.EngagementID,
		arg.SourceType,
		arg.OriginalFilename,
		arg.StorageUri,
		arg.Sha256,
		arg.ScanDate,
		arg.ParserVersion,
		arg.UploadedBy,
	)
	var i ScanReport
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.SourceType,
		&i.OriginalFilename,
		&i.StorageUri,
		&i.Sha256,
		&i.ScanDate,
		&i.IngestedAt,
		&i.ParserVersion,
		&i.ParseStatus,
		&i.ParseError,
		&i.FindingCount,
		&i.UploadedBy,
	)
	return i, err
}

const getScanReport = `-- name: GetScanReport :one
SELECT id, engagement_id, source_type, original_filename, storage_uri, sha256, scan_date, ingested_at, parser_version, parse_status, parse_error, finding_count, uploaded_by FROM scan_reports WHERE id = $1
`

func (q *Queries) GetScanReport(ctx context.Context, id int64) (ScanReport, error) {
	row := q.db.QueryRowContext(ctx, getScanReport, id)
	var i ScanReport
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.SourceType,
		&i.OriginalFilename,
		&i.StorageUri,
		&i.Sha256,
		&i.ScanDate,
		&i.IngestedAt,
		&i.ParserVersion,
		&i.ParseStatus,
		&i.ParseError,
		&i.FindingCount,
		&i.UploadedBy,
	)
	return i, err
}

const getScanReportBySha = `-- name: GetScanReportBySha :one
SELECT id, engagement_id, source_type, original_filename, storage_uri, sha256, scan_date, ingested_at, parser_version, parse_status, parse_error, finding_count, uploaded_by FROM scan_reports
WHERE engagement_id = $1 AND sha256 = $2
`

type GetScanReportByShaParams struct {
	EngagementID int64  `json:"engagement_id"`
	Sha256       string `json:"sha256"`
}

func (q *Queries) GetScanReportBySha(ctx context.Context, arg GetScanReportByShaParams) (ScanReport, error) {
	row := q.db.QueryRowContext(ctx, getScanReportBySha, arg.EngagementID, arg.Sha256)
	var i ScanReport
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.SourceType,
		&i.OriginalFilename,
		&i.StorageUri,
		&i.Sha256,
		&i.ScanDate,
		&i.IngestedAt,
		&i.ParserVersion,
		&i.ParseStatus,
		&i.ParseError,
		&i.FindingCount,
		&i.UploadedBy,
	)
	return i, err
}

const listScanReports = `-- name: ListScanReports :many
SELECT id, engagement_id, source_type, original_filename, storage_uri, sha256, scan_date, ingested_at, parser_version, parse_status, parse_error, finding_count, uploaded_by FROM scan_reports
WHERE engagement_id = $1
ORDER BY ingested_at DESC
LIMIT $2 OFFSET $3
`

type ListScanReportsParams struct {
	EngagementID int64 `json:"engagement_id"`
	Limit        int64 `json:"limit"`
	Offset       int64 `json:"offset"`
}

func (q *Queries) ListScanReports(ctx context.Context, arg ListScanReportsParams) ([]ScanReport, error) {
	rows, err := q.db.QueryContext(ctx, listScanReports, arg.EngagementID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanReport
	for rows.Next() {
		var i ScanReport
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.SourceType,
			&i.OriginalFilename,
			&i.StorageUri,
			&i.Sha256,
			&i.ScanDate,
			&i.IngestedAt,
			&i.ParserVersion,
			&i.ParseStatus,
			&i.ParseError,
			&i.FindingCount,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanReportStatus = `-- name: UpdateScanReportStatus :exec
UPDATE scan_reports
SET parse_status = $2, parse_error = $3, finding_count = $4
WHERE id = $1
`

type UpdateScanReportStatusParams struct {
	ID           int64          `json:"id"`
	ParseStatus  ParseStatus    `json:"parse_status"`
	ParseError   sql.NullString `json:"parse_error"`
	FindingCount int32          `json:"finding_count"`
}

func (q *Queries) UpdateScanReportStatus(ctx context.Context, arg UpdateScanReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanReportStatus,
		arg.ID,
		arg.ParseStatus,
		arg.ParseError,
		arg.FindingCount,
	)
	return err
}
