// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scope_violations.sql

package database

import (
	"context"
	"database/sql"
)

const listScopeViolations = `-- name: ListScopeViolations :many
SELECT id, flow_id, engagement_id, tool_name, target, occurred_at FROM scope_violations
WHERE engagement_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListScopeViolationsParams struct {
	EngagementID sql.NullInt64 `json:"engagement_id"`
	Limit        int64         `json:"limit"`
	Offset       int64         `json:"offset"`
}

func (q *Queries) ListScopeViolations(ctx context.Context, arg ListScopeViolationsParams) ([]ScopeViolation, error) {
	rows, err := q.db.QueryContext(ctx, listScopeViolations, arg.EngagementID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeViolation
	for rows.Next() {
		var i ScopeViolation
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.EngagementID,
			&i.ToolName,
			&i.Target,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScopeViolation = `-- name: RecordScopeViolation :exec
INSERT INTO scope_violations (flow_id, engagement_id, tool_name, target)
VALUES ($1, $2, $3, $4)
`

type RecordScopeViolationParams struct {
	FlowID       sql.NullInt64 `json:"flow_id"`
	EngagementID sql.NullInt64 `json:"engagement_id"`
	ToolName     string        `json:"tool_name"`
	Target       string        `json:"target"`
}

func (q *Queries) RecordScopeViolation(ctx context.Context, arg RecordScopeViolationParams) error {
	_, err := q.db.ExecContext(ctx, recordScopeViolation,
		arg.FlowID,
		arg.EngagementID,
		arg.ToolName,
		arg.Target,
	)
	return err
}
